<a href="https://colab.research.google.com/github/Shreyas-13/Tensorflow-Developer/blob/main/000_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 🛠: 00. TensorFlow Fundamentals Exercises

#### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [ ]:
import tensorflow as tf
import numpy as np

scalar = tf.constant(np.random.randint(1,10))

vector = tf.constant(np.arange(1,10))

matrix = tf.constant(np.arange(1,10).reshape(3,3))

tensor = tf.constant(np.arange(1,19).reshape(2,3,3))

print(scalar)
print(vector)
print(matrix)
print(tensor)

#### 2. Find the shape, rank and size of the tensors you created in 1

In [7]:
def func(tensor):
  print('Shape = ', tensor.shape)
  print('Rank = ', tensor.ndim)
  print('Size = ', tf.size(tensor))

func(tensor)

Shape =  (2, 3, 3)
Rank =  3
Size =  tf.Tensor(18, shape=(), dtype=int32)


#### 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [8]:
tf.random.set_seed(30)
tensor1 = tf.random.Generator.from_seed(42)
tensor1 = tensor1.uniform(shape=(5,300))

tensor2 = tf.random.Generator.from_seed(52)
tensor2 = tensor2.uniform(shape=(5,300))

print(tensor1)
print(tensor2)

tf.Tensor(
[[0.7493447  0.73561966 0.45230794 ... 0.5816356  0.5627874  0.7491298 ]
 [0.6438937  0.6938418  0.04408407 ... 0.04825139 0.5099728  0.26470542]
 [0.21373153 0.6683699  0.78474844 ... 0.19658887 0.22030771 0.3766911 ]
 [0.68190825 0.29304636 0.5415933  ... 0.37111604 0.76053166 0.7538099 ]
 [0.8011551  0.48830473 0.13867617 ... 0.20301867 0.8378159  0.19984365]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.5914326  0.21738243 0.5322075  ... 0.678746   0.09103632 0.6027968 ]
 [0.2354095  0.79634094 0.16588712 ... 0.3354292  0.45307434 0.18366218]
 [0.70624435 0.27036226 0.92301977 ... 0.52282226 0.4796052  0.40956295]
 [0.7639382  0.9208015  0.96507776 ... 0.3171805  0.2562983  0.98411655]
 [0.5639552  0.5084231  0.02382088 ... 0.7537936  0.4346373  0.5250298 ]], shape=(5, 300), dtype=float32)


#### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [9]:
mult = tf.matmul(tf.transpose(tensor1), tensor2)
mult

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.7184637 , 1.7686661 , 1.3800777 , ..., 1.6565326 , 0.98543984,
        1.7492056 ],
       [1.5696902 , 1.4112504 , 1.4179646 , ..., 1.5425018 , 0.9892264 ,
        1.3893675 ],
       [1.3240626 , 0.9148022 , 1.498356  , ..., 1.0083892 , 0.6366025 ,
        1.2079502 ],
       ...,
       [0.8922    , 0.6629557 , 0.86200243, ..., 0.7844937 , 0.35245237,
        0.9117978 ],
       [1.6619842 , 1.7142788 , 1.3413957 , ..., 1.5409973 , 0.94701946,
        1.7114692 ],
       [1.4599769 , 1.271201  , 1.5225427 , ..., 1.1839359 , 0.648852  ,
        1.5012287 ]], dtype=float32)>

#### 5. Multiply the two tensors you created in 3 using dot product.

In [11]:
mult = tf.tensordot(tf.transpose(tensor1), tensor2, axes=1)
mult

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.7184637 , 1.7686661 , 1.3800777 , ..., 1.6565326 , 0.98543984,
        1.7492056 ],
       [1.5696902 , 1.4112504 , 1.4179646 , ..., 1.5425018 , 0.9892264 ,
        1.3893675 ],
       [1.3240626 , 0.9148022 , 1.498356  , ..., 1.0083892 , 0.6366025 ,
        1.2079502 ],
       ...,
       [0.8922    , 0.6629557 , 0.86200243, ..., 0.7844937 , 0.35245237,
        0.9117978 ],
       [1.6619842 , 1.7142788 , 1.3413957 , ..., 1.5409973 , 0.94701946,
        1.7114692 ],
       [1.4599769 , 1.271201  , 1.5225427 , ..., 1.1839359 , 0.648852  ,
        1.5012287 ]], dtype=float32)>

#### 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [12]:
tensor3 = tf.random.Generator.from_seed(2)
tensor3 = tensor3.uniform(shape=(224,224,3))
tensor3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95810425, 0.55623317, 0.16466296],
        [0.13445711, 0.13229859, 0.5348098 ],
        [0.57090175, 0.50970507, 0.48252344],
        ...,
        [0.01353109, 0.2823602 , 0.0927937 ],
        [0.2424469 , 0.92214036, 0.1318667 ],
        [0.18895125, 0.13469017, 0.29916108]],

       [[0.22880554, 0.02310789, 0.3042692 ],
        [0.7830497 , 0.21773398, 0.12459803],
        [0.7456944 , 0.8774493 , 0.7112646 ],
        ...,
        [0.14082742, 0.41235518, 0.45162737],
        [0.6804353 , 0.04887676, 0.6775023 ],
        [0.29143417, 0.3466624 , 0.17450547]],

       [[0.38451958, 0.33060753, 0.73888445],
        [0.4587338 , 0.81736076, 0.15108037],
        [0.60569584, 0.93234086, 0.10864663],
        ...,
        [0.3923154 , 0.4012767 , 0.25327802],
        [0.7235824 , 0.51754737, 0.32620752],
        [0.09840012, 0.3233775 , 0.9681879 ]],

       ...,

       [[0.85072494, 0.95170057, 0.44895744],
        [0.16

#### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [23]:
tf.reduce_max(tensor3), tf.reduce_min(tensor3)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99998736>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>)

#### 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [25]:
tensor4 = tf.random.Generator.from_seed(3)
tensor4 = tensor4.uniform(shape=(1, 224, 224, 3))
print(tensor4.shape)

tensor4_squeezed = tf.squeeze(tensor4)
print(tensor4_squeezed.shape)

(1, 224, 224, 3)
(224, 224, 3)


#### 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [27]:
tensor5 = tf.random.Generator.from_seed(32)
tensor5 = tensor5.uniform(shape=[10])

print(tf.argmax(tensor5), tf.argmin(tensor5))

tf.Tensor(5, shape=(), dtype=int64) tf.Tensor(1, shape=(), dtype=int64)


#### 10. One-hot encode the tensor you created

In [29]:
tensor6 = tf.constant(np.random.randint(9, size=9))
tensor6

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([6, 3, 2, 3, 6, 1, 7, 1, 5])>

In [32]:
oneHot = tf.one_hot(tensor6, depth = 8)
oneHot

<tf.Tensor: shape=(9, 8), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>