<a href="https://colab.research.google.com/github/Shreyas-13/Tensorflow-Developer/blob/main/00_Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamentals

Outline:
* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and Numpy
* Using @tf.function(a way to speed up regular python func)
* Using GPU with tensorflow

# Intro to Tensors

### Creating tensors using `tf.constant`

In [16]:
import tensorflow as tf

print(tf.__version__)

##Creating a tensor
scalar = tf.constant(7)
scalar

2.8.0


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [17]:
#Creating a vector

vector = tf.constant([13,2], dtype=tf.float16)
vector

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([13.,  2.], dtype=float16)>

In [18]:
vector.ndim

1

In [19]:
#Creating a matrix

matrix = tf.constant([[10,20],
                      [20,30],
                     [30,40]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [20, 30],
       [30, 40]], dtype=int32)>

In [20]:
matrix.ndim

2

In [21]:
#Creating a 3-D tensor

tensor = tf.constant([[[10,20,30],
                       [20,30,40]],
                      [[13,2,2000],
                       [13,2,2001]],
                      [[16,11,2002],
                       [12,12,12]],
                      [[12,23,43],
                      [12,45,76]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[  10,   20,   30],
        [  20,   30,   40]],

       [[  13,    2, 2000],
        [  13,    2, 2001]],

       [[  16,   11, 2002],
        [  12,   12,   12]],

       [[  12,   23,   43],
        [  12,   45,   76]]], dtype=int32)>

In [22]:
tensor.ndim

3

* scalar: A variable with single value
* vector: A set of values in single dimension[a single subscript is requiured hence 1-D]
* matrix: A set of vector having 2-dimension[2 subscripts required hence 2-D e.g. arr[0][0]]
* tensor: A set of matrices having n-dimension(dimension refers to the no. of digits required to indicate a particular element in an array)

### Creating tensors with `tf.Variable`

In [23]:
tf.Variable

tensorflow.python.ops.variables.Variable